#!/bin/bash
# Establish a reverse SSH tunnel from realtime machine to remote server

# Load:
# - remote server address as user@address, REMOTEADDR
# - remote server port to use, RPORT
# - local port to connect back to, LPORT
# - location of private key file, PRIVATEKEY
if [[ "$#" -ne 1 ]]; then
  echo "$(basename $0) seaflow-realtime.conf"
  exit 1
fi
CONFFILE=$1
if [[ ! -e "$CONFFILE" ]]; then
  echo "Config file $CONFFILE does not exist"
  exit 1
fi

source "$CONFFILE"

# On SSH server set
#   ClientAliveInterval 60
#   ClientAliveCountMax 3
# to make sure the local reverse tunnel on the server end shuts down if the
# network connection is lost for 3 minutes.
date
/usr/bin/ssh -i "$PRIVATEKEY" \
  -o ConnectTimeout=60 \
  -o ExitOnForwardFailure=True \
  -o ServerAliveInterval=60 \
  -o ServerAliveInterval=3 -N -T -R"$RPORT":localhost:"$LPORT" "$REMOTEADDR" 2>&1
