#!/bin/bash
# Heartbeat of SeaFlow realtime computer phoning home


# Load:
# - remote server address as user@address, REMOTEADDR
# - location of private key file, PRIVATEKEY
if [[ "$#" -ne 1 ]]; then
  echo "$(basename $0) seaflow-realtime.conf"
  exit 1
fi
CONFFILE=$1
if [[ ! -e "$CONFFILE" ]]; then
  echo "Config file $CONFFILE does not exist"
  exit 1
fi

source "$CONFFILE"

ssh -i "$PRIVATEKEY" "$REMOTEADDR" bash -c "date >>heartbeat/heartbeat.$CRUISE.$SERIAL.txt"
