#!/bin/bash
# Sync realtime analysis results files to an off-ship server using rsync over
# SSH.

# Load:
# - location of directory to sync, RESULTSDIR
# - remote server address as user@address, REMOTEADDR
# - location of private key file, PRIVATEKEY
if [[ "$#" -ne 1 ]]; then
  echo "$(basename $0) seaflow-realtime.conf"
  exit 1
fi
CONFFILE=$1
if [[ ! -e "$CONFFILE" ]]; then
  echo "Config file $CONFFILE does not exist"
  exit 1
fi

source "$CONFFILE"

date
/usr/bin/rsync -auvz -e "/usr/bin/ssh -i \"$PRIVATEKEY\"" \
  --progress --stats --partial \
  "$RESULTSDIR/sync/"{stats.csv,sfl.csv} "${REMOTEADDR}:sync/" 2>&1
