---

# These must exist in order for nomad to start
- name: Create nomad host volume directories
  become: yes
  file:
    path: "{{ item }}"
    owner: "{{ realtime_user }}"
    group: "{{ realtime_user }}"
    state: directory
  loop:
    - "{{ jobs_data }}"
    - "{{ local_jobs_data }}"

- name: Install nomad host volume configuration
  become: yes
  template:
    src: host_volume.hcl.j2
    dest: /etc/nomad.d/host_volume.hcl
    owner: nomad
    group: nomad
  notify: Restart nomad

# Put in nomad systemd env file and /etc/environment to make sure env is set up
# for cases where service starts a job and where realtime user starts a job.
- name: Set system-wide nomad docker user environment variable
  become: yes
  lineinfile:
    path: "{{ item }}"
    line: "NOMAD_VAR_realtime_user={{ realtime_user }}"
  loop:
    - /etc/nomad.d/nomad.env
    - /etc/environment
  notify: Restart nomad

- name: Create realtime configuration directory
  become: yes
  file:
    path: /etc/realtime
    state: directory
    recurse: yes
    mode: 0755
    owner: "{{ realtime_user }}"
    group: "{{ realtime_user }}"

- name: Install nomad jobs
  become: yes
  copy:
    src: nomad-jobs
    dest: /etc/realtime
    owner: "{{ realtime_user }}"
    group: "{{ realtime_user }}"

- name: Install nomad management scripts
  become: yes
  copy:
    src: scripts
    dest: /etc/realtime
    owner: "{{ realtime_user }}"
    group: "{{ realtime_user }}"
