---
# tasks file for docker

- name: Ensure previous docker packages are uninstalled
  become: yes
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    update_cache: yes
    cache_valid_time: 1800

- name: Install Apt prereqs
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: present
    update_cache: yes
    cache_valid_time: 1800

- name: Add docker Apt signing key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Get Ubuntu codename
  command: lsb_release -cs
  register: codename_result
  check_mode: no
  changed_when: False

- name: Add Docker package repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ codename_result.stdout }} stable"
    filename: "docker.list"
    state: present
    update_cache: yes

- name: Install docker
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
    cache_valid_time: 1800

- name: Add the ansible user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Reset SSH connection to register docker group addition
  meta: reset_connection

- name: Run Docker hello world
  command: docker run --rm hello-world
  register: hello_world_result
  check_mode: no
  changed_when: False

- name: Install Python Docker SDK
  pip:
    name: docker
