- hosts: all
  become: yes

  pre_tasks:
    - name: "Install apt prerequisites"
      apt:
        state: present
        name:
          - jq
          - samba
          - cifs-utils
          - smbclient
        update_cache: yes
        cache_valid_time: 1800

    - include_role:
        name: consul

    - include_role:
        name: nomad

  roles:
    - hashicorp-realtime
